/*
 * Brave Data Insights API
 * Brave Data Insights is an API that delivers real-time insights for better risk and fraud decisions. Our API can obtains one or more insights based on data collected from the user's mobile devices or web applications.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.brave.dataevents.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.brave.dataevents.client.model.Source;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DatasetBasicDataModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-14T22:11:48.456525056Z[GMT]")

public class DatasetBasicDataModel {
  @SerializedName("dataId")
  private String dataId = null;

  @SerializedName("sourceId")
  private Source sourceId = null;

  @SerializedName("uploadDate")
  private String uploadDate = null;

  public DatasetBasicDataModel dataId(String dataId) {
    this.dataId = dataId;
    return this;
  }

   /**
   * Identifier of dataset
   * @return dataId
  **/
  @Schema(example = "web-570e8420-e29b-41d4-a436-1266104409", description = "Identifier of dataset")
  public String getDataId() {
    return dataId;
  }

  public void setDataId(String dataId) {
    this.dataId = dataId;
  }

  public DatasetBasicDataModel sourceId(Source sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @Schema(description = "")
  public Source getSourceId() {
    return sourceId;
  }

  public void setSourceId(Source sourceId) {
    this.sourceId = sourceId;
  }

  public DatasetBasicDataModel uploadDate(String uploadDate) {
    this.uploadDate = uploadDate;
    return this;
  }

   /**
   * Date when data set has been collected
   * @return uploadDate
  **/
  @Schema(example = "2023-06-02T21:50Z", description = "Date when data set has been collected")
  public String getUploadDate() {
    return uploadDate;
  }

  public void setUploadDate(String uploadDate) {
    this.uploadDate = uploadDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetBasicDataModel datasetBasicDataModel = (DatasetBasicDataModel) o;
    return Objects.equals(this.dataId, datasetBasicDataModel.dataId) &&
        Objects.equals(this.sourceId, datasetBasicDataModel.sourceId) &&
        Objects.equals(this.uploadDate, datasetBasicDataModel.uploadDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataId, sourceId, uploadDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetBasicDataModel {\n");
    
    sb.append("    dataId: ").append(toIndentedString(dataId)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    uploadDate: ").append(toIndentedString(uploadDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
