/*
 * Brave Data Insights API
 * Brave Data Insights is an API that delivers real-time insights for better risk and fraud decisions. Our API can obtains one or more insights based on data collected from the user's mobile devices or web applications.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.brave.dataevents.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WebAppDataModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-14T22:11:48.456525056Z[GMT]")

public class WebAppDataModel implements OneOfDatasetInsightDataModelModulesItems {
  @SerializedName("code")
  private String code = null;

  @SerializedName("value")
  private Object value = null;

  public WebAppDataModel code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Fragment configuration code
   * @return code
  **/
  @Schema(example = "web_application", description = "Fragment configuration code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public WebAppDataModel value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Extracted value
   * @return value
  **/
  @Schema(example = "{   \"browserName\": \"Chrome\",   \"deviceBrand\": \"Apple\",   \"browserLanguage\": \"en\",   \"mouseMovingSpeed\": \"376.682811004854\",   \"browserTimezoneName\": \"America/Mexico_City\",   \"keyboardTypingSpeed\": \"8.68935527543819\",   \"clickRageActionsCount\": \"0\",   \"clickTotalEventsCount\": \"13\",   \"deviceOperatingSystem\": \"Mac OS X\",   \"mouseMovingPathLength\": \"3309.53509270973\",   \"mouseRageActionsCount\": \"0\",   \"touchRageActionsCount\": null,   \"touchTotalEventsCount\": null,   \"inputPasteActionsCount\": \"0\",   \"scrollTotalEventsCount\": \"0\",   \"browserIsAdblockEnabled\": \"0\",   \"deviceScreenOrientation\": \"0\",   \"inputDeleteActionsCount\": \"0\",   \"keyboardRageActionsCount\": \"1\",   \"appFormFillingTimeSpentTotal\": \"9.81700015068054\",   \"keyboardDeleteKeyPressedCount\": \"0\",   \"keyboardTotalKeysPressedCount\": \"12\",   \"browserIsIncognitoModeDetected\": \"false\",   \"keyboardLetterKeysPressedCount\": \"0\",   \"keyboardNumberKeysPressedCount\": \"12\",   \"appFormFillingTimeSpentEffective\": \"9.81700015068054\",   \"keyboardBackspaceKeyPressedCount\": \"0\",   \"appFormFillingTrackedEventsPerSec\": \"34.5466496208718\" }", description = "Extracted value")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebAppDataModel webAppDataModel = (WebAppDataModel) o;
    return Objects.equals(this.code, webAppDataModel.code) &&
        Objects.equals(this.value, webAppDataModel.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebAppDataModel {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
